---
repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.22.9
    hooks:
      - id: typos

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
