---
extends: default

# These files are imported by vale from an external repository
ignore: |
  .vale/styles/RedHat/
rules:
  truthy:
    # the node "on:" present in each GitHub Actions workflow file
    ignore: |
      .github/

  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
