---
# golangci-lint configuration file made by @ccoVeille
# Source: https://github.com/ccoVeille/golangci-lint-config-examples/tree/main/00-empty
# License: MIT
#
# empty file to force using the default settings
# otherwise golangci-lint looks for .golangci.yaml files
# in parent folders
# this may cause issues
