---
name: CI
on:
  pull_request:
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-action
        uses: actions/checkout@v4

      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v19
