---
name: CI
on:
  pull_request:
jobs:
  typos-cli:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-action
        uses: actions/checkout@v4

      - name: typos-action
        uses: crate-ci/typos@v1
