---
name: CI
on:
  pull_request:
jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-action
        uses: actions/checkout@v4

      # mitigate some issues with the vale-action
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: vale-action
        uses: errata-ai/vale-action@v2
