---
name: CI
on:
  pull_request:
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-action
        uses: actions/checkout@v4

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
